#!/usr/bin/env bash
# bash script

echo $$ > /var/run/myscript.pid

handle_sigterm() {
    echo "I hate the kill command"
    cleanup_and_exit
}

handle_sigint() {
    echo "Y U no love me?!"
}

handle_sigquit() {
    cleanup_and_exit
}

cleanup_and_exit() {
    rm -f /var/run/myscript.pid
    exit 0
}

trap handle_sigterm SIGTERM
trap handle_sigint SIGINT
trap handle_sigquit SIGQUIT

while true; do
    echo "To infinity and beyond"
    sleep 2
done
