#!/usr/bin/env bash
# a Bash script that displays Best School 10 times, Hi on the 9th

counter=1
while [ $counter -le 10 ]
do
    if [ $counter -eq 9 ]; then
        echo "Best School"
        echo "Hi"
    else
        echo "Best School"
    fi
    ((counter++))
done

exit 0
